### ISSUE TITLE
Test File rate limit

### ISSUE THREAD

**Issue by x-delfino** [scalar/openapi-parser#102]
### What happens?

Look's like some of the test file downloads hit the rate limit before being added in https://github.com/scalar/openapi-parser/pull/75 e.g. [brazecom.yaml](https://github.com/scalar/openapi-parser/blob/4351d85b00a2241037aca8a02ef6c7faeb1c4e37/packages/openapi-parser/tests/files/brazecom.yaml)

Doing a search for `<!doctype html>`, it looks like quite a few files are affected.

### What did you expect to happen?

Test files to be valid yaml

### How can we reproduce the issue?

1. Search `repo:scalar/openapi-parser <!doctype html>`
2. Check instances of rate limit errors e.g. [brazecom.yaml](https://github.com/scalar/openapi-parser/blob/4351d85b00a2241037aca8a02ef6c7faeb1c4e37/packages/openapi-parser/tests/files/brazecom.yaml)

**Comment by hanspagel** [comment]
Oops, yes! I should add some error handling to the script and run it again.
