### ISSUE TITLE
Create new issue links to the /discussions section of this repo, but it's disabled

### ISSUE THREAD

**Issue by tmcw** [scalar/openapi-parser#157]
### What happens?

The new issues chooser https://github.com/scalar/openapi-parser/issues/new/choose - refers to discussions, to open a new one, but that link is a 404 because discussions are not enabled.

### What did you expect to happen?

Discussions should be enabled

### How can we reproduce the issue?

Try to create a feature request

### Swagger/OpenAPI Example

https://

**Comment by hanspagel** [comment]
Enabled :)
